### ISSUE TITLE
[feature] 쿼리 분석 및 성능 개선

### ISSUE THREAD

**Issue by YJGwon** [YJGwon/connectruck#143]
### Description

- application에서 발생하는 쿼리를 확인하고 분석한 뒤 최적화하여 API 성능 개선

### To-do

- [ ] 각 service별 발생 쿼리 분석
- [ ] JPA 쿼리 최적화
- [ ] DB index 최적화

### Due Date

2023-09-24
